version: '2'
services:
  cloud9:
    build: ./cloud9
    volumes:
      - ./workspace:/workspace/
    ports:
      - "3010:80"
  php:
    build: ./php
    ports:
      - "3110:80"
    volumes:
      - ./workspace/www:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=my_database
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3210:3306"
 
